"""change_daily_to_monthly_summary

Revision ID: 575af1005a43
Revises: bbb92a37ef54
Create Date: 2025-11-15 22:28:52.309449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575af1005a43'
down_revision: Union[str, None] = 'bbb92a37ef54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip constraint operations for SQLite compatibility
    # op.create_unique_constraint('uq_family_category_name', 'categories', ['family_id', 'name'])
    # op.create_foreign_key(None, 'categories', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    
    # Rename columns by adding new and copying data
    op.add_column('users', sa.Column('monthly_summary_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('monthly_summary_time', sa.String(length=5), nullable=True))
    
    # Copy data from old columns to new (if they exist)
    try:
        op.execute('UPDATE users SET monthly_summary_enabled = daily_summary_enabled')
        op.execute('UPDATE users SET monthly_summary_time = daily_summary_time')
    except:
        pass  # Columns might not exist yet
    
    # Drop old columns
    try:
        op.drop_column('users', 'daily_summary_enabled')
        op.drop_column('users', 'daily_summary_time')
    except:
        pass  # Columns might not exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the changes
    op.add_column('users', sa.Column('daily_summary_time', sa.VARCHAR(length=5), nullable=True))
    op.add_column('users', sa.Column('daily_summary_enabled', sa.BOOLEAN(), server_default='0', nullable=False))
    
    # Copy data back
    try:
        op.execute('UPDATE users SET daily_summary_enabled = monthly_summary_enabled')
        op.execute('UPDATE users SET daily_summary_time = monthly_summary_time')
    except:
        pass
    
    op.drop_column('users', 'monthly_summary_time')
    op.drop_column('users', 'monthly_summary_enabled')
    # Skip constraint operations for SQLite compatibility
    # op.drop_constraint(None, 'categories', type_='foreignkey')
    # op.drop_constraint('uq_family_category_name', 'categories', type_='unique')
    # ### end Alembic commands ###

