"""add_user_settings_fields

Revision ID: bbb92a37ef54
Revises: ec4db506fd7f
Create Date: 2025-11-15 22:15:06.743040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb92a37ef54'
down_revision: Union[str, None] = 'ec4db506fd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping temporary table and constraint modifications as SQLite doesn't support them
    # op.drop_table('_alembic_tmp_categories')
    # op.create_unique_constraint('uq_family_category_name', 'categories', ['family_id', 'name'])
    # op.create_foreign_key(None, 'categories', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    
    # Add new columns to users table with default values
    op.add_column('users', sa.Column('currency', sa.String(length=3), server_default='₽', nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default='Europe/Moscow', nullable=False))
    op.add_column('users', sa.Column('date_format', sa.String(length=20), server_default='DD.MM.YYYY', nullable=False))
    op.add_column('users', sa.Column('daily_summary_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('daily_summary_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_summary_time')
    op.drop_column('users', 'daily_summary_enabled')
    op.drop_column('users', 'date_format')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'currency')
    # Skip constraint and table operations as SQLite doesn't support them well
    # op.drop_constraint(None, 'categories', type_='foreignkey')
    # op.drop_constraint('uq_family_category_name', 'categories', type_='unique')
    # op.create_table('_alembic_tmp_categories', ...)
    # ### end Alembic commands ###

