"""add_family_id_to_categories

Revision ID: ec4db506fd7f
Revises: 184b2c95e4b3
Create Date: 2025-11-15 15:24:35.782877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4db506fd7f'
down_revision: Union[str, None] = '184b2c95e4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Using batch mode for SQLite compatibility
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_categories_family', ['family_id'], unique=False)
        batch_op.create_unique_constraint('uq_family_category_name', ['family_id', 'name'])
        batch_op.create_foreign_key('fk_categories_family_id', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Using batch mode for SQLite compatibility
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_family_id', type_='foreignkey')
        batch_op.drop_constraint('uq_family_category_name', type_='unique')
        batch_op.drop_index('ix_categories_family')
        batch_op.drop_column('family_id')
    # ### end Alembic commands ###

